### ISSUE TITLE
Fix @lintr-bot comments

### ISSUE THREAD

**Issue by richelbilderbeek** [Neves-P/utilSIE#8]
I enjoy this repo and staying informed.

Now the Travis build works, @lintr-bot will offer its helpful comments and I will receive an email for each push. I understand the cleaning up can start from this this moment on and not earlier.

I would appreciate fixing the @lintr-bot comments, due to getting those emails. Sure, there's no rush :+1:

**Comment by richelbilderbeek** [comment]
I assign @Neves-P, as I assume he wrote the not-yet-checked-by-@lintr-bot code, so he'll be the one the improve his style even more :+1:

**Comment by Neves-P** [comment]
Last thing missing is: `no visible global function definition`, will fix tonight or tomorrow.

Thanks, @richelbilderbeek ! 👍

**Comment by richelbilderbeek** [comment]
Good job Pedro!
